apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /foo
        pathType: ImplementationSpecific
        backend:
          service:
            name: echo
            port:
              number: 80
      - path: /graph/hello
        backend:
          service: 
            name: kong_blazegraph
      - path: /graph?
        backend:
          service:
            name: kong_blazegraph_api_query_post
      - path: /graph-full-access?
        backend:
          service:
            name: kong_blazegraph_api_query_post_full_access
      - path: /annotation/hello
        backend:
          service:
            name: kong_miiify
      - path: /annotation/
        backend:
          service:
            name: kong_miiify_add_anotation
      