apiVersion: networking.k8s.io/v1 # https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/getting-started/
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: //kong_blazegraph:8080/bigdata/#splash
    http:
      paths:
        - path: /graph/hello
          pathType: ImplementationSpecific
          backend:
            service: 
              name: kong_blazegraph
    - host: //kong_blazegraph:8080/bigdata/sparql
      http:
        paths:
        - path: /graph?
          pathType: ImplementationSpecific
          backend:
            service:
              name: kong_blazegraph_api_query_post
    - host: //kong_blazegraph:8080/bigdata/sparql
      http:
        paths:
        - path: /graph-full-access?
          pathType: ImplementationSpecific
          backend:
            service:
              name: kong_blazegraph_api_query_post_full_access
    - host: //kong_miiify:8080
      http:
        paths:
        - path: /annotation/hello
          pathType: ImplementationSpecific
          backend:
            service:
              name: kong_miiify
    - host: //kong_miiify:8080/annotations/
      http:
        paths:
        - path: /annotation/
          pathType: ImplementationSpecific
          backend:
            service:
              name: kong_miiify_add_anotation
      