apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
        - name: vue-frontend
          image: 259004456259.dkr.ecr.eu-west-2.amazonaws.com/ohos-observatory-frontend:v_14
          #image: local/image_testing_attempt
          #imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: vue-frontend
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000