apiVersion: v1
kind: Service
metadata:
  name: vue-frontend
  labels:
    app: vue-frontend
spec:
  ports:
    - port: 3000
      name: vue-frontend
  clusterIP: None
  selector:
    app: vue-frontned