apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  ports:
    - port: 3000 
      name: react-frontend
  clusterIP: None
  selector:
    app: react-frontend