apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: 259004456259.dkr.ecr.eu-west-2.amazonaws.com/go-api:latest
          ports:
            - containerPort: 5000
              name: go-api
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000