FROM golang:1.18-alpine
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go ./
RUN go build -o /ohos-go-api
EXPOSE 9090
#RUN go run .
#CMD ["run", "go", "."]
CMD ["/ohos-go-api"]
#CMD ["go", "run", "."]