apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: proxy
  selector:
    app: kong
    tier: frontend
  type: LoadBalancer
