apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  KONG_DATABASE_KEY: "off"
  KONG_PROXY_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG_KEY: "/dev/stdout"
  KONG_PROXY_ERROR_LOG_KEY: "/dev/stdout"
  KONG_ADMIN_ERROR_LOG_KEY: "/dev/stdout"
  KONG_PROXY_LISTEN_KEY: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
  KONG_ADMIN_LISTEN_KEY: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_DECLARATIVE_CONFIG_KEY: "/etc/config/kong.yml"
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:

      - name: blazegraph-hello
        url: https://blazegraph/bigdata/#splash
        port: 3497
        routes:
          - name: blazegraph-hello
            paths:
              - /graph/hello
            strip_path: true
            methods:
              - GET       

      - name: blazegraph-public-query
        url: https://blazegraph/bigdata/sparql
        port: 3497
        routes:
          - name: blazegraph-public
            paths:
              - /graph?
            preserve_host: true
            strip_path: true
            methods:
              - GET

      - name: blazegraph-full-access
        url: https://blazegraph/bigdata/sparql
        port: 3497
        routes:
          - name: blazegraph-full-access
            paths: 
              - /graph-full-access?
            preserve_host: true
            strip_path: true
            methods:
              - GET
              - POST
              - DELETE

      - name: miiify
        url: https://miiify
        port: 8080
        routes:
          - name: root
            paths:
              - /v1
              - /
            preserve_host: true
            methods:
              - GET
              - HEAD
              - OPTIONS
              
      - name: iiif-generator
        url: https://iiif-generator
        port: 5050
        routes:
          - name: iiif-generator
            paths:
              - /annotation/
            strip_path: true
            preserve_host: true
            methods:
              - POST
              - GET