apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: 259004456259.dkr.ecr.eu-west-2.amazonaws.com/go-api:latest
          ports:
            - containerPort: 5000
              name: goapi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000