apiVersion: apps/v1
kind: Deployment
metadata:
  name: miiify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miiify
  template:
    metadata:
      labels:
        app: miiify
    spec:
      containers:
        - name: miiify
          image: jptmoore/miiify
          args: ["--config=/etc/config/config.json"]
          ports:
            - containerPort: 8080
              name: miiify
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
